### ISSUE TITLE
Towards the next release

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#323]
**Note**: the base functions of Franklin are basically all there (`serve, optimize, ...`) and fairly stable, small things are changing which are more related  to what it can parse + what it can do when parsing, these things are generally added as "patch releases" as they're unlikely to affect anyone apart from the one(s) who asked for that specific behaviour. In theory these should be minor releases but that would happen too often. So basically my philosophy is to do a minor release when "a few" such new things are added and I'm generally happy with the state of things. 
All of this stuff is backward compatible in the sense that if your site worked before, it will work after. For a summary of 'important' changes see NEWS.md. The only place where a real break happened was in the 0.5 -> 0.6 transition. No such major transition is planned for the near future.

#### features

* [ ] page snippets for a "recent posts" page (a la hugo etc) that parses  katex properly for preview etc. Support for chronological posts.
* [x] taxonomy (tag pages) (PR: #481 ; minor release)
* [ ] (brainstorm) consider merging of CSS into one if several are called in `head.html` by default (e.g. vela) --> can use purgecss hook for this
* [ ] don't fail if page foot is  not defined or empty.

#### Docs

* [ ] on_write  (example from wikunia)
* [ ] `globvar`, `locvar`, `pagevar` + return nothing if unknown
* [ ] `lx_, `hfun_` and the `utils.jl` file
* [ ] taxonomy
* [ ] multiple class with `@@` so `@@c1,c2 ... @@`
* [ ] custom content stuff with page vars (content_tag, content_div, content_id) see @findmyway 's PR and #521 
* [ ] clarify the `internal` thing with `fd2html` since people seem to use this more and more
* [ ] can use regex to ignore folders (@Wikunia 's changes brought in #522) 
* [ ] anchors brought in via `\label` have a class `anchor` (so that can offset a fixed navbar)
* [ ] addition of a `host` keyword to `serve` (exposing an addition in liveserver @cserteGT3 )
* [ ] **removal** of `\underline` see #512 use `\style` instead
* [ ] addition of `{{isempty xx}` and `{{isnotempty xx}}` blocks #514 

#### Code quality

* [ ] more tests
  * [ ] some tests from common mark (issue #313)

**Comment by findmyway** [comment]
> lx_, hfun_and the utils.jl` file

Can we also have a place to collect some common and inspiring code snippets?

For example, in the https://github.com/tlienart/franklindocs/blob/master/config.md there's a `note` command which is very useful. And @Wikunia also mentioned an interesting `\showdiff` command in his [blog](https://opensourc.es/blog/Franklin.jl/)

**Comment by tlienart** [comment]
so many good ideas!

**Comment by Wikunia** [comment]
I'm happy to help. Will work on something probably Monday maybe earlier. Would like to fill the currently empty Utils.jl page with basic explanation of lx and hfun and maybe an examples section.
