### ISSUE TITLE
Name change todo

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#340]
* [x] release 0.4.3 with deprecation warning (#339) 
* [x] get a new UUID
* [x] update whatever needs updating in the code so that tests pass with `Franklin` module
* [x] ([wip](https://github.com/JuliaRegistries/General/pull/8085)) tag a Franklin.jl 0.4.4 and register it
* [x] migrate `JuDocWeb` to something else like `franklindocs` 
* [x] get new UUID for  JuDocTemplates and change names to FranklinTemplates
* [x] ([wip](https://github.com/JuliaRegistries/General/pull/8095)) register FranklinTemplates (can re-start from 0.1 this time to avoid issues, doesn't matter)
* [x] test the whole lot works
* [x] change  `jd*` functions for  `fd*` functions  (e.g. `fd2html`, with understanding that a `.fd` could be a `franklin-doc`.  
* [x] verify docs website in  depth
* [x] release a  `0.5` as all this is breaking
* [ ] update MLJTutorials
* [x] update website
* [x] write short guide of what people may  bump against (`.jd-content` -> `.franklin-content`, `.jd-toc` -> `.franklin-toc`; `jd2html` -> `fd2html`; `{{fill jd_mtime}}` --> `{{fill fd_mtime}}`,

**Comment by tlienart** [comment]
Ok this is now done with the minor release of `Franklin 0.5` and  corresponding  `FranklinTemplates 0.4.2`. Thanks to  @Wikunia for help along the way and finding a sneaky bug in the `highlight.pack.js` (now fixed). I apologise to anyone who may have encountered additional bugs and problems during the transition.

@cormullion , @cserteGT3 , @abhishalya, tk3369 pinging you guys as well for a heads up (sorry), here are the [few short steps](https://github.com/tlienart/Franklin.jl/releases/tag/v0.5.0) to go from JuDoc to Franklin. Let me know if you encounter an issue, thanks!

PS: I will soon fix the issue with the stray `/pub/` in URLs (#335) but should manage to  do  this in a backward compatible manner. You may want to watch that issue for a ping when it's solved.

**Comment by Wikunia** [comment]
The steps worked for me. I think `index.html` should/can be deleted as well, right?

**Comment by tlienart** [comment]
You can  but that's not really necessary, it'll  be overwritten, however if you've written your own `src/index.html` for a custom landing page, then the same rules apply, but you just need to modify that there (i.e. modify  `src/index.html`) and it will  overwrite the existing one. If you have the standard `src/index.md` then you can safely just do the  steps mentioned above. 

Thanks for reporting that it worked for you!

**Comment by tk3369** [comment]
@tlienart Thanks for the heads-up.  I just went live with my site yesterday using Franklin 0.4.4 (caught it just when it got registered 😛 )  

I will follow your instructions and bring it up to Franklin 0.5 later.

**Comment by cormullion** [comment]
No problems updating. I'm sorry you had to rename everything but perhaps there will some benefits down the line... Thanks for the upgrade instructions and for all your hard work!
