### ISSUE TITLE
GitHub deployment mayhem

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#645]
From fiddling around with the `deploy.yml` it seems that

1. For simple cases (single user), just don't use SSH so remove the `webfactory/` stuff and at the end use `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` (e.g. [cormullion's site](https://github.com/cormullion/cormullion.github.io/blob/dev/.github/workflows/deploy.yaml), [this example](https://github.com/tlienart2/myWebsite/blob/master/.github/workflows/deploy.yml) and [this example](https://github.com/tlienart2/tlienart2.github.io/blob/dev/.github/workflows/deploy.yml))

It's a bit unclear when that's "not enough", it might not be enough for org websites (at least I couldn't get that running for the julialang website but that might just be another issue altogether)

1. For more complex cases (org websites), it seems that the above might not work and that SSH *is* required. In that case users should imitate the [setup from julialang website](https://github.com/JuliaLang/www.julialang.org/blob/master/.github/workflows/deploy.yml) which uses SSH: https://github.com/JuliaLang/www.julialang.org/blob/master/.github/workflows/deploy.yml it seems the format of the key matters, they should use PEM and not OpenSSL it seems that the following should be enough:

```
ssh-keygen -m PEM -N "" -f franklin
```

and to copy the content of the private `franklin` to `secrets.FRANKLIN_PRIV`... 

this second case unfortunately needs more testing. 

also #644 

### Todo

* [ ] figure out what's going on
* [ ] use solution (1) in FranklinTemplates since it'll work for most people
* [ ] get feedback from people for which it doesn't work and adjust
